# =====================================================================
#  asp_timing.xdc  -  timing and physical constraints, XC7Z020.
#
#  Written to be read top to bottom while building the project.  Every
#  constraint says WHY it exists; a constraint whose reason is not
#  recorded is a constraint nobody dares remove later.
#
#  Scope: the PL datapath (asp_top).  The AD9361 interface timing comes
#  from the Analog Devices IP's own XDC when that reference design is
#  used - do not duplicate it here, or the two sets will disagree.
# =====================================================================

# ---------------------------------------------------------------------
# 1. CLOCKS
# ---------------------------------------------------------------------
# The datapath clock is generated by the Clocking Wizard from the AD9361
# DATA_CLK.  create_generated_clock is NOT written here: the Clocking
# Wizard emits it for its own output, and hand-writing a second
# definition is the classic way to end up with two clocks on one net.
#
# What IS needed is the source clock, if the board file does not already
# provide it.  245.760 MHz is the AD9361 LVDS DDR data clock at
# 61.44 MSPS x 2 x 2; adjust to the rate actually configured.
#
# create_clock -name data_clk -period 4.069 [get_ports DATA_CLK_P]

# Convenience handle for everything below.  Using a wildcard on the MMCM
# output rather than a port name keeps this file valid whether the
# clocking wizard is instantiated in the block design or in RTL.
set clk_dsp [get_clocks -of_objects [get_pins -hierarchical -filter {NAME =~ *clk_wiz*/inst/mmcm_adv_inst/CLKOUT0}]]

# ---------------------------------------------------------------------
# 2. CLOCK GROUPS - the only asynchronous boundary in the design
# ---------------------------------------------------------------------
# The PS AXI clock (FCLK_CLK0) and clk_dsp are unrelated: clk_dsp must be
# derived from the AD9361 sample clock so that every rate in the datapath
# is an exact integer ratio, and the PS PLL cannot produce that.
#
# The crossing is handled by ONE AXI Clock Converter instance.  Declaring
# the groups asynchronous tells the tool not to attempt to time across
# it; the IP's own internal constraints cover its synchronisers.
#
# If this is omitted, Vivado will try to time ~2000 paths between two
# unrelated clocks, report enormous negative slack, and the real timing
# problems will be invisible underneath it.
set_clock_groups -asynchronous \
  -group [get_clocks -include_generated_clocks clk_fpga_0] \
  -group [get_clocks -include_generated_clocks -of_objects \
          [get_pins -hierarchical -filter {NAME =~ *clk_wiz*/inst/mmcm_adv_inst/CLKOUT0}]]

# ---------------------------------------------------------------------
# 3. RESET
# ---------------------------------------------------------------------
# aresetn is asserted asynchronously and released synchronously by the
# two-flop synchroniser in asp_top.  The asynchronous assert path has no
# meaningful setup requirement, so it is cut; the release edge is timed
# normally through rst_sync.
set_false_path -to [get_pins -hierarchical -filter {NAME =~ *p_rst*rst_meta_reg*/PRE}]
set_false_path -to [get_pins -hierarchical -filter {NAME =~ *p_rst*rst_meta_reg*/CLR}]

# The datapath reset is high fanout by nature (it reaches every control
# register in ten blocks).  Let the tool replicate it rather than fight
# a single net across the die; 512 is low enough to force replication and
# high enough not to explode the register count.
set_property MAX_FANOUT 512 [get_nets -hierarchical -filter {NAME =~ *u_dp*rst*}]

# ---------------------------------------------------------------------
# 4. PATHS TO WATCH  (informational - review these first if WNS is
#    negative after the first implementation run)
# ---------------------------------------------------------------------
# The datapath is heavily pipelined and its arithmetic sits inside DSP48
# slices, so the streaming stages are not the risk.  Three paths that
# previously stacked a long combinational cone into one FSM state have
# been split across states in the RTL (still NOT multicycle-constrained):
#
#   a) asp_weight_calc / S_BF_PK + S_BF_PK_CH
#      Peak magnitude over eight 48-bit values, one channel (two abs +
#      two compares) per clock.
#
#   b) asp_whiten / S_NORM + S_NORM_SH
#      Max of four diagonal entries, then ceil(log2) on the next clock.
#
#   c) asp_tx_scale / p_agc
#      Fast acquisition is a 5-step binary search (one 96-bit compare
#      against a constant threshold per clock) plus a hysteresis cycle.
#      Must finish inside the 8-clk FS_WORK sample gap after the dwell
#      tick — budget is 7 clocks.
#
# None of these is constrained as a multicycle path, and that is
# deliberate: the finite state machines advance every clock, so a
# multicycle exception would be simply WRONG rather than optimistic.

# ---------------------------------------------------------------------
# 5. AD9361 PARALLEL INTERFACE
# ---------------------------------------------------------------------
# Only needed if the ADI axi_ad9361 IP is NOT used and a custom SelectIO
# front end is built instead.  Values are placeholders and MUST be taken
# from the AD9361 data sheet for the configured data rate; leaving them
# at these numbers and hoping is how an interface passes in simulation
# and fails on the bench.
#
# set_input_delay  -clock data_clk -max 1.50 [get_ports {rx_data[*]}]
# set_input_delay  -clock data_clk -min 0.20 [get_ports {rx_data[*]}]
# set_output_delay -clock data_clk -max 1.20 [get_ports {tx_data[*]}]
# set_output_delay -clock data_clk -min 0.10 [get_ports {tx_data[*]}]

# ---------------------------------------------------------------------
# 6. IMPLEMENTATION STRATEGY NOTES
# ---------------------------------------------------------------------
# Resource estimate for XC7Z020 (85K logic cells, 220 DSP48E1, 140
# BRAM36, 106400 FF, 53200 LUT):
#
#   DSP48E1   ~85   39%   mixer 4, FIR 32, covariance 16, EVD 8,
#                         weights 6, beamformer 4, misc 15
#   BRAM36      0    0%   every delay line is registers or SRL
#   FF      ~19000   18%
#   LUT     ~13000   24%
#
# There is no BRAM in the datapath at all, which is worth noting because
# it means the whole design can be placed without competing with a DMA
# buffer or a PS cache path for block RAM columns.
#
# The FIR delay line (248 x 32 bits) is the largest single structure.
# It is written as a plain shift register with taps every fourth stage
# so Vivado can map the four-deep runs between taps into SRL16
# primitives; that is why the delay line is NOT reset - an SRL has no
# reset input, and adding one would force ~8000 flip-flops instead.
# If utilisation reports show those as FDRE rather than SRL, check that
# no reset has crept onto them.
#
# Suggested first run:
#   synth_design  -directive Default
#   opt_design    -directive Explore
#   place_design  -directive Default
#   phys_opt_design
#   route_design  -directive Default
# With ~24% LUT and no BRAM contention, congestion should not be an
# issue; if it is, the FIR adder tree is the structure to look at.
