function amb = asp_array_ambiguity(pos, lambda, gridN)
%ASP_ARRAY_AMBIGUITY Peak grating response of a planar array over the visible region.
%
%   AMB = ASP_ARRAY_AMBIGUITY(POS, LAMBDA, GRIDN)
%
%   AMB.peakLevelDB   highest off-mainlobe value of the array factor, in dB
%                     relative to the peak.  0 dB means a full ambiguity:
%                     two distinct arrival directions produce IDENTICAL
%                     array responses, so a null steered at one of them is
%                     also steered at the other.
%   AMB.peakDelta     the (du,dv) direction-cosine offset where it occurs
%   AMB.peakSepDeg    the corresponding angular separation for a source at
%                     zenith, in degrees
%   AMB.mainlobeNullU first null of the mainlobe in direction-cosine units,
%                     which is the natural measure of NULL WIDTH
%   AMB.ambiguous     true if peakLevelDB > -3 dB
%
%   WHY THE MAX-BASELINE RULE OF THUMB IS WRONG
%   -------------------------------------------
%   "Keep every baseline under lambda/2" is the rule most people carry over
%   from linear arrays.  For a PLANAR array it is both wrong and expensive.
%   The array response is
%
%       a_i(u,v) = exp(j 2 pi (x_i u + y_i v)/lambda),   u^2 + v^2 <= 1
%
%   and two directions are indistinguishable iff their direction-cosine
%   difference D satisfies (p_i - p_j).D/lambda in Z for every pair.  The
%   set of such D is the DUAL LATTICE of the lattice generated by the
%   baseline vectors, scaled by lambda.  Ambiguity therefore appears when
%   the shortest non-zero dual vector falls inside the visible disk |D| <= 2,
%   which depends on the LATTICE, not on the longest baseline.
%
%   Two consequences that matter for this product:
%
%   * A square lattice of side d aliases when d >= lambda/2, so a 2x2 array
%     is capped at 9.5 cm sides at L1 and a max baseline of 0.707*lambda.
%
%   * A TRIANGULAR lattice of side d aliases only when d >= 2*lambda/sqrt(3)
%     = 1.155*lambda/2, i.e. it tolerates 15.5% more spacing - and a
%     3-elements-on-a-ring-plus-centre layout generates exactly a triangular
%     lattice.  At a ring radius of lambda/2 it stays unambiguous while
%     reaching a 0.866*lambda maximum baseline, 22% more aperture than the
%     square for the same four elements and the same radome.  This is the
%     familiar hexagonal-sampling advantage from 2-D signal processing,
%     applied to the aperture rather than to an image.
%
%   Wider aperture means a narrower spatial null, which means fewer
%   authentic satellites caught in it.  That is measurable: see
%   studies/study_array_size.m.

if nargin < 3 || isempty(gridN)
    gridN = 401;
end

% Array factor as a function of the direction-cosine DIFFERENCE D.  Because
% a(u1)'*a(u2) depends only on u2-u1, one 2-D evaluation covers every pair.
g = linspace(-2, 2, gridN);
[DU, DV] = meshgrid(g, g);
inDisk = (DU.^2 + DV.^2) <= 4 + 1e-12;

n = size(pos,2);
AF = zeros(size(DU));
for i = 1:n
    AF = AF + exp(1i*2*pi*(pos(1,i)*DU + pos(2,i)*DV)/lambda);
end
AF = abs(AF)/n;
AF(~inDisk) = -Inf;

% Mainlobe extent: walk out from the origin until the array factor first
% drops below 1/sqrt(2), then keep excluding until it stops decreasing.
rad = sqrt(DU.^2 + DV.^2);
mainR = firstNullRadius(pos, lambda);
mask = inDisk & (rad > mainR);

[peak, idx] = max(AF(mask));
AFmasked = AF; AFmasked(~mask) = -Inf;
[~, linIdx] = max(AFmasked(:));

amb.peakLevelDB = 20*log10(max(peak, realmin));
amb.peakDelta   = [DU(linIdx), DV(linIdx)];
amb.peakSepDeg  = 2*asind(min(norm(amb.peakDelta)/2, 1));
amb.mainlobeNullU = mainR;
amb.ambiguous   = amb.peakLevelDB > -3;
amb.gridN       = gridN;

end

% -------------------------------------------------------------------------
function r = firstNullRadius(pos, lambda)
%FIRSTNULLRADIUS Radius, in direction-cosine units, of the first minimum of
%   the array factor, averaged over azimuth.  This is the natural measure of
%   how wide a projection null is: a satellite whose direction cosine is
%   within r of the spoofer's will be significantly attenuated.
nAz = 36;
rr = zeros(1,nAz);
n = size(pos,2);
for k = 1:nAz
    th = (k-1)/nAz*2*pi;
    dirv = [cos(th); sin(th)];
    s = linspace(0, 2, 800);
    af = zeros(size(s));
    for i = 1:n
        af = af + exp(1i*2*pi*(pos(1:2,i).'*dirv)*s/lambda);
    end
    af = abs(af)/n;
    % first local minimum
    idx = find(diff(af) > 0, 1, 'first');
    if isempty(idx), idx = numel(s); end
    rr(k) = s(idx);
end
r = mean(rr);
end
